# Generated by Django 5.0.7 on 2025-02-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
