# Generated by Django 5.0.7 on 2025-03-21 02:41

import pages.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=pages.storages.ImageLocalStorage(), upload_to='uploads/')),
            ],
        ),
    ]
